# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/gptansh/53defcabbad9276c362af23bd3fcb1df/untitled9.ipynb
"""

import nltk
import csv
import numpy as np
nltk.download('punkt')

from google.colab import drive
drive.mount("/content/gdrive")

cd gdrive/My Drive/Notes/ml/basic sentiment analysis/NLP

ls

negative = []
with open("words_negative.csv", "r") as file:
    reader = csv.reader(file)
    for row in reader:
        negative.append(row)

negative[:10]

positive = []
with open("words_positive.csv", "r") as file:
    reader = csv.reader(file)
    for row in reader:
        positive.append(row)

def sentiment_analysis(text):
  temp=[]
  text_to_sentences = nltk.sent_tokenize(text)
  for sentence in text_to_sentences:
    nw_count = 0
    pw_count =0
    sentence_to_words = nltk.word_tokenize(sentence)
    for word in sentence_to_words:
            for item in positive:
                if(word == item[0]):
                    pw_count +=1
            for item in negative:
                if(word == item[0]):
                    nw_count +=1
    if(pw_count>0 and nw_count==0):
      temp.append(1)
    elif(nw_count%2 == 1):
      temp.append(-1)
    elif(nw_count%2 ==0 and nw_count > 0):
      temp.append(1)
    else:
      temp.append(0)
  return temp

sentiment_analysis("the corona effect in india is making every thing bad")

mylist = sentiment_analysis("I saw this movie the other night. I can say I was not disappointed! The actiing and story line was amazing and kept me on the edge of my seat the entire time. While I did not care for the music, it did not take away from the overall experience. I would highly recommend this movie to anyone who enjoys thirllers.")

mylist

avg = np.average(mylist)

avg

views=[]
with open("reviews.csv", "r") as file:
    reader = csv.reader(file)
    for row in reader:
        views.append(row)

views

views[0]

for analyize in views:
  x=np.average(sentiment_analysis(str(analyize)))
  print(np.average(sentiment_analysis(str(analyize))),end=" ")
  if(x>=(-0.1) and x<=0.1):
    print("Neutral")
  elif(x>0.1 and x<=0.6):
    print("Quite Positive")
  elif(x<=1 and x>0.6):
    print("Positive")
  elif(x<-0.1 and x>=-0.6):
    print("Quite Negative")
  elif(x>=-1 and x<-0.6):
    print("Negative")  
        
  print(analyize)
  print("\n")

